language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

sudo: required
dist: trusty

services:
    - docker

cache:
  directories:
    - $HOME/.cache/bower
    - $HOME/.composer/cache
    - $HOME/.npm
    - /tmp/phantomjs
    - tools

env:
  global:
    - CORE_BRANCH=stable10
    - APP_NAME=guests
  matrix:
    - DB=sqlite

branches:
  only:
    - master

before_install:
  - wget https://raw.githubusercontent.com/owncloud/administration/master/travis-ci/before_install.sh
  - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
  - docker pull mailhog/mailhog
  - docker run -d -i -p 8025:8025 -p 1025:1025 -t mailhog/mailhog

  # Add some output debugging information
  - cd ../core
  - ./occ check
  - ./occ status
  - ./occ app:list

script:
  - cd apps/$APP_NAME/tests/integration
  - ./run.sh

matrix:
  include:
    - php: 7.1
      env: DB=sqlite CORE_BRANCH=master
    - php: 7.2
      env: DB=sqlite CORE_BRANCH=master
  fast_finish: true
